# Generated by Django 4.0.10 on 2024-04-06 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='registered_at',
            new_name='registred_at',
        ),
    ]
